
package fruit.health.server.auditlog;

public enum AuditEvent
{
    APP_ACCESSED,
    BROWSER_ID_GENERATED,

    USER_SIGNUP,
    USER_LOGIN,
    USER_LOGOUT,
    USER_PASSWORD_CHANGE,
    USER_RELOGIN,

    USER_PASSWD_RESET_REQUEST,
    USER_PASSWD_RESET_COMPLETE,
    USER_EMAIL_CHANGE_REQUEST,
    USER_EMAIL_CHANGE_COMPLETED,

    SECURITY_FAILED_LOGIN_ATTEMPT,
    SECURITY_FAILED_BROWSER_LOGIN_ATTEMPT,

    EMAIL_SENT
}
