package fruit.health.client.util;

public enum TimedEvent
{
    /* Events that time startup times */
    PAGE_START_TO_JS_START, PAGE_START_TO_GWT_START, PAGE_START_TO_MODULE_START, PAGE_START_TO_MODULE_LOAD_END, PAGE_START_TO_GATHERING_INITIAL_LOGIN_RELATED_STATE, PAGE_START_TO_HISTORY_HANDLING, PAGE_START_TO_FIRST_ACTIVITY_START,

    VIEW_CREATION, RPC_CALL, ACTIVITY_CREATION,
}
