package fruit.health.client.util;

public enum TimedEvent
{
    /* Events that time startup times */
    JS_START_TO_GWT_START, JS_START_TO_MODULE_START, JS_START_TO_MODULE_LOAD_END, JS_START_TO_GATHERING_INITIAL_LOGIN_RELATED_STATE, JS_START_TO_HISTORY_HANDLING, JS_START_TO_FIRST_ACTIVITY_START,

    VIEW_CREATION, RPC_CALL, ACTIVITY_CREATION,
}
